server:
  port: 18082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.33.128:3306/guli_sms
    username: root
    password: 123456
  redis:
    port: 6379
    host: 192.168.33.128


feign:
  sentinel:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.atguigu.gmall.sms.entity
  mapper-locations: classpath:mapper/sms/**/*.xml
